name: Node CI Workflow
# The parameters are defaulted at the org level but can be overridden on the repository.
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:
    inputs:
      workflowBranch:
        description: 'Branch of the reusable workflow. Defaults to main, select dev for testing only.'
        required: true
        default: 'main'
        type: choice
        options:
          - dev
          - main
env:     
  IS_LINT_REQUIRED: false
  IS_FORMAT_CHECK_REQUIRED: false
  IS_UNIT_TESTS_REQUIRED: false

permissions:
  issues: write
  pull-requests: write

jobs:
  ci-dev:
    if: ${{ github.event.inputs.workflowBranch == 'dev' }}
    uses: shardeum/github-automation/.github/workflows/node-ci-shared.yml@dev
    secrets: inherit

  ci-main:
    if: ${{ github.event.inputs.workflowBranch == 'main' || !github.event.inputs.workflowBranch }}
    uses: shardeum/github-automation/.github/workflows/node-ci-shared.yml@main
    secrets: inherit

  
