name: Node CI Workflow

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  set-branch: # Job to determine the branch name and set it as an output
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.set-branch.outputs.branch }}
    steps:
      - name: Set workflow branch
        id: set-branch
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          if [ "$BRANCH_NAME" == "main" ]; then
            echo "branch=main" >> $GITHUB_OUTPUT
          else
            echo "branch=dev" >> $GITHUB_OUTPUT
          fi
  
  ci-dev:
    needs: set-branch
    if: ${{ needs.set-branch.outputs.branch == 'dev' }}
    uses: shardeum/github-automation/.github/workflows/node-ci-shared.yml@RED-120
    with:
      node-version: '18.16.1'
      lint-required: false # TODO: enable lint check after lint is fixed
      format-check-required: false # TODO: enable format check after format is fixed
      apply-patches-required: true
      unit-tests-required: false # TODO: enable unit tests after unit tests are fixed
  ci-main:
    needs: set-branch
    if: ${{ needs.set-branch.outputs.branch == 'main' }}
    uses: shardeum/github-automation/.github/workflows/node-ci-shared.yml@RED-120
    with:
      node-version: '18.16.1'
      lint-required: false # TODO: enable lint check after lint is fixed
      format-check-required: false # TODO: enable format check after format is fixed
      apply-patches-required: true
      unit-tests-required: false # TODO: enable unit tests after unit tests are fixed